### ISSUE TITLE
getConfig function potentially helpful

### ISSUE THREAD

**Issue by JTronLabs** [rblopes/phaser-plus-template#4]
I usually define these functions so getting/setting simple key/value pairs is a safer task. I imagine it'd make transitioning to a local SQLite or making a web call easier in the long run (though I have not personally had to do this yet). I define these functions in Boot or Preload.

```javascript
//define getters/setters to change configuration variables. This makes it simple to transition to SQL in an app later on, if so desired
this.game.getConfig = function(name){
  return localStorage[name];
};
this.game.setConfig = function(name, value){
  return localStorage[name] = value;
};
```

**Comment by rblopes** [comment]
This kind of functionality is more fit for a Phaser plugin. Adding some helper functions like these may be good for early prototyping stages, but not much else.

Perhaps implementing a custom plugin over a library like [PouchDB] or [localForage] may give better results in the long run. These libraries abstract from the IndexedDB API. localForage can use DOM Storage (localStorage) too.

There is also a plugin by Orange Games called [phaser-super-storage].

I prefer not to ship functions like these right into the sample game because of the caveats they may introduce. For example, it is OK use localStorage for storing trivial values. localStorage serializes everything to strings, however, and these may not be immediately an issue if you only store values using `JSON.stringify`, for example. And since browser vendors never agree on a common implementation for these features, using a well documented, battle-tested library is a better alternative anyway.

[PouchDB]: https://pouchdb.com/
[localForage]: https://localforage.github.io/localForage
[phaser-super-storage]: https://github.com/orange-games/phaser-super-storage

**Comment by JTronLabs** [comment]
I agree about using  a library over local storage. The reason I think a global function would be helpful would be to provide 1 point of control over how you store configs, and allow user to transition away from it. Regardless, you make good points.

Thank you for those links. I had heard of PouchDB but not the others, very cool!
